name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build -- --configuration production --base-href /Users/davidrl/Downloads/projects/estudionoventayseis/

      - name: Move files to /dist and remove /dist/angular-estudionoventayseis
        run: mv dist/browser/* dist/

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
